---
esphome:
  name: $devicename
  platform: ESP8266
  board: esp01_1m
  on_boot:
  - output.turn_on: relay

#Enable WiFi fallback/captive portal in case there's an isssue
wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
  fast_connect: true
  ap:
    ssid: ${friendly_name}
    password: !secret ap_password

captive_portal:

# Disable UART logging as it interferes with cse7766
logger:
  baud_rate: 0

api:
  password: !secret api_password

ota:
  password: !secret ota_password

uart:
  rx_pin: RX
  baud_rate: 4800

binary_sensor:
  - platform: gpio
    pin:
      number: GPIO0
      mode: INPUT_PULLUP
      inverted: True
    name: "${friendly_name} Pushbutton"
    internal: true
    on_press:
      - switch.toggle: relay_2

  - platform: status
    name: "${friendly_name} Status"

sensor:
  - platform: wifi_signal
    name: "${friendly_name} WiFi Signal"
    update_interval: 60s

  - platform: cse7766
    current:
      name: "${friendly_name} Current"
      unit_of_measurement: A
      accuracy_decimals: 2
    voltage:
      name: "${friendly_name} Voltage"
      unit_of_measurement: V
      accuracy_decimals: 2
    power:
      name: "${friendly_name} Wattage"
      unit_of_measurement: W
      accuracy_decimals: 2
    update_interval: 10s

output:
  - platform: gpio
    pin: GPIO12
    id: relay

status_led:
  pin: GPIO13

# This stays fixed to be toggled by the pushbutoton
switch:
  - platform: gpio
    name: "relay_2"
    pin: GPIO12
    id: relay_2
    internal: True